version: '3.2'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: application_web:1.0
    depends_on:
      - db
    command: ["/home/django/scripts/wait_for_postgres.sh"]
    environment:
      PRODUCTION: 'true'
    expose:
      - "5959"
    logging:
      driver: "json-file"
    volumes:
      - ../application:/app
  nginx:
    restart: always
    container_name: application_nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ../application/static:/static
      - ../application/media:/media
    depends_on:
      - django_web
    ports:
      - "0.0.0.0:80:80"